services:
  - type: web
    name: resume-genie-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false